name: Hourly cron job
on:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request POST \
          --url 'https://blog.errong.win/api/graphql' \
          --header 'Content-Type: application/json' \
          --data '{"operationName":null,"variables":{},"query":"{\n  posts(offset: 0) {\n    items {\n      title\n      plaintext\n      slug\n    }\n    hasMore\n    count\n  }\n}\n"}'
